const ADMIN_NAME = "Kimpes";
const ADMIN_PASSWORD_HASH =
  "$2b$10$Vn5lH/.fhqW729yVSwLXaO38Fxv9PpFZy0QQH6kRTP6BZZdyXlRc.";
const MAX_TITLE_LENGTH = 256;
const MAX_DESCRIPTION_LENGTH = 1024;
const FAQ_ENTRIES_PER_PAGE = 5;
const BLOG_POSTS_PER_PAGE = 2;
const WORK_ENTRIES_PER_PAGE = 2;

exports.constantVariables = {
  ADMIN_NAME,
  ADMIN_PASSWORD_HASH,
  MAX_TITLE_LENGTH,
  MAX_DESCRIPTION_LENGTH,
  FAQ_ENTRIES_PER_PAGE,
  BLOG_POSTS_PER_PAGE,
  WORK_ENTRIES_PER_PAGE,
};
